oname: Ma première Action
on: [push]

env: 
  DAY_OF_WEEK: Monday

jobs:
  Explorer-Actions-Github:
    runs-on: ubuntu-latest
    env: 
      Greenting: Hello
    steps:
    - name: " Say hello Mona it's Monday "
      run : echo "$Greenting $First_Name $DAY_OF_WEEK!"
      env: 
        First_Name: Mona
    - name: "Say scret"
      run: echo ${{secrets.MY_SECRET}}
  
