name: test my secret

on: [push]

jobs:
  test-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du repository
        uses: actions/checkout@v4

      - name: Lister les fichiers pour debug
        run: ls -R  # Affiche tous les fichiers et leur emplacement

      - name: Vérifier le secret
        run: python scripts/verifier_secret.py  # Adapte le chemin si nécessaire
        env:
          MON_SECRET: ${{ secrets.MY_SECRET }}

